### ISSUE TITLE
Buffer.write(string, encoding, offset[, length]) is no longer supported

### ISSUE THREAD

**Issue by haoyuant** [electron/mini-breakpad-server#17]
I use the Electron CrashReporter and set the submitURL to "http://localhost:1127/post". When I use `process.crash()`, the server throws this error:

Error [ERR_NO_LONGER_SUPPORTED]: Buffer.write(string, encoding, offset[, length]) is no longer supported
    at Buffer.write (buffer.js:931:11)
    at MultipartParser.initWithBoundary (/Users/haoyuantang/Downloads/mini-breakpad-server-master/node_modules/formidable/lib/multipart_parser.js:61:17)
    at IncomingForm._initMultipart (/Users/haoyuantang/Downloads/mini-breakpad-server-master/node_modules/formidable/lib/incoming_form.js:326:10)
    at IncomingForm._parseContentType (/Users/haoyuantang/Downloads/mini-breakpad-server-master/node_modules/formidable/lib/incoming_form.js:269:12)
    at IncomingForm.writeHeaders (/Users/haoyuantang/Downloads/mini-breakpad-server-master/node_modules/formidable/lib/incoming_form.js:142:8)
    at IncomingForm.parse (/Users/haoyuantang/Downloads/mini-breakpad-server-master/node_modules/formidable/lib/incoming_form.js:110:8)
    at Function.Record.createFromRequest (/Users/haoyuantang/Downloads/mini-breakpad-server-master/lib/record.js:36:19)
    at Object.exports.saveRequest (/Users/haoyuantang/Downloads/mini-breakpad-server-master/lib/saver.js:13:19)
    at /Users/haoyuantang/Downloads/mini-breakpad-server-master/lib/app.js:56:18
    at Layer.handle [as handle_request] (/Users/haoyuantang/Downloads/mini-breakpad-server-master/node_modules/express/lib/router/layer.js:95:5)

**Comment by jinq0123** [comment]
```
npm WARN deprecated formidable@1.0.17: Old versions of Formidable are not compatible with the current Node.js; Upgrade to 1.2.0 or later
```
So I changed package.json:
```
[jinqing@host-192-168-21-31 mini-breakpad-server]$ git diff package.json
diff --git a/package.json b/package.json
index d298a50..465cd0b 100644
--- a/package.json
+++ b/package.json
@@ -16,7 +16,7 @@
     "dirty": "0.9.7",
     "express": "^4.14.1",
     "express-json": "^1.0.0",
-    "formidable": "~1.0.14",
+    "formidable": "~1.2.0",
     "fs-plus": "0.10.0",
     "github-releases": "0.1.x",
     "glob": "3.x",
```

**Comment by haoyuant** [comment]
Yea, doing a dependencies update can fix the problem, thanks.
